import turtle
print ("Nevi")
print ("Nevi"*3)
print ("Nevi"*100)
number1 = 6
print (number1)
number2 = number1/2
print (number2)
a = [46,3,18]
for apple in a:
	print (apple)
for apple in a:
	print (apple*2)
n =sum(a)
print (n)
'''turtle.penup()
turtle.begin_fill()
turtle.goto(0,100)
turtle.pendown()
turtle.goto(100,100)
turtle.goto(100,0)
turtle.goto(0,0)
turtle.goto(0,100)
turtle.end_fill()'''
turtle.penup()
turtle.goto(-250,100)
turtle.pendown()
turtle.circle(100)
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.circle(100)
turtle.penup()
turtle.goto(250,100)
turtle.pendown()
turtle.circle(100)
turtle.penup()
turtle.goto(130,0)
turtle.pendown()
turtle.circle(100)
turtle.penup()
turtle.goto(-130,0)
turtle.pendown()
turtle.circle(100)
turtle.mainloop()